---
title:                                  Chevrette Lab
tagline:                                Research Overview
date:                                   2022-06-04 00:00:00
description: >
                                        What we do.

tags:                                   [ Overview ]
categories:                             [ Research, Science ]

scrollbar:                              false

permalink:                              /pages/public/research_overview/site/
regenerate:                             false

resources:                              [ animate, scroller ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /mc_assets/gator1.jpg
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:badges-enabled:                        false

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ifeval::[{badges-enabled} == true]
{badge-j1--license} {badge-j1--version-latest} {badge-j1-gh--last-commit} {badge-j1--downloads}
endif::[]

// Include sub-documents (if any)
// -----------------------------------------------------------------------------

== Research in the _Chevrette Lab_ is focused broadly on _secondary metabolism_ and how it relates to _interspecies interactions_. 

'''

=== We study secondary metabolism...

=== _in evolution_

* Genome mining, including the development of new computational tools to identify and characterize biosynthetic gene clusters (BGCs) in microbial genomes
* Diversity and distribution of BGCs and biosynthetic enzymes across evolutionary space
* Ancestral reconstruction of biosynthetic domains, genes, and pathways
* Evolutionary dynamics of enzyme specificity and promiscuity

=== _in natural systems_
* Secondary metabolites and BGCs...
** from host-associated microbiomes, including amphibian skin, insect exoskeleton, and the rhizosphere
** from soil bacteria, including those from Tiny Earth (see https://tinyearth.wisc.edu)

=== _in experimental systems_
* Metatranscriptomics and metametabolomics of synthetic microbial communities
* Genetic and regulatory mechanisms of secondary metabolite expression and interspecies interactions
* Specificity of interactions across synthetic microbial communities
