---
title:                                  Chevrette Lab
tagline:                                Lab Alumni
date:                                   2022-06-04 00:00:00
description: >
                                        Who we were.

tags:                                   [ Overview ]
categories:                             [ Team ]

scrollbar:                              false

permalink:                              /pages/public/team/alum/site/
regenerate:                             false

resources:                              [ animate, scroller ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/clab/uw/bascom_sunrise.png
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:badges-enabled:                        false

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ifeval::[{badges-enabled} == true]
{badge-j1--license} {badge-j1--version-latest} {badge-j1-gh--last-commit} {badge-j1--downloads}
endif::[]

// Include sub-documents (if any)
// -----------------------------------------------------------------------------

:headshot_size: 250
:icon_size: 32
:c1ratio: 1
:c2ratio: 3

== Former Staff
[cols=".^{c1ratio},.^{c2ratio}"]
|===
a|*Layla Schuster*
a|2022-2025, UF, Scientist

a|*Mark Ou*
a|2022-2025, UF, Lab Manager

a|*Melinda Chue Donahey*
a|2022-2025, UF, Scientist
|===


== Former Postdoctoral Associates
[cols=".^{c1ratio},.^{c2ratio}"]
|===
a|*Denni (Svienn) Einarsson*
a|2022-2024, UF
|===

== Former Graduate Students
[cols=".^{c1ratio},.^{c2ratio}"]
|===
a|*José DD Cediel Becerra*
a|2022-2025, UF Microbiology & Cell Science

a|*Sebastian Guerra*
a|2022-2025, UF Genetics & Genomics

a|*Murrel Saldanha*
a|2023-2025, UF Microbiology & Cell Science

|===

== Former Undergraduate and Postbaccalaureate Trainees
[cols=".^{c1ratio},.^{c2ratio}"]
|===
a|*Kellie Rice*
a|2025, UF

a|*Ayana Febles*
a|2024-2025, UF

a|*Sabrina Hernandez*
a|2024-2025, UF, American Society for Pharmacognosy Summer Research Fellow

a|*Shannon Manning*
a|2023-2025, UF

a|*Neha Kashyap*
a|2023-2025, UF

a|*Julia Charske*
a|2023, UF

a|*Ma Andrea Gatmaitan*
a|2023, UF, American Society for Pharmacognosy Summer Research Fellow
|===

== Former Visiting Scientists & Trainees
[cols=".^{c1ratio},.^{c2ratio}"]
|===
a|*Eduardo Sánchez Carvajal*
a|2024-2025, Universidad Téchnica Federico Santa Maria

a|*Jordi Weijers*
a|2024-2025, Leiden University

a|*Abbi Tate*
a|2024, Newcastle University

a|*Javier Gil*
a|2023, Miami Dade College

a|*Lidimarie Trujillo Rodríguez*
a|2022-2023, University of Florida
|===


'''

link:/pages/public/team/current/site/[Current team]