---
title:                                  Chevrette Lab
tagline:                                Join us!
date:                                   2022-06-04 00:00:00
description: >
                                        Join our team!

tags:                                   [ Overview ]
categories:                             [ Team, Contact ]

scrollbar:                              false

permalink:                              /pages/public/join_us/site/
regenerate:                             false

resources:                              [ animate, scroller ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/clab/uw/bascom_sunrise.png
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:badges-enabled:                        false

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ifeval::[{badges-enabled} == true]
{badge-j1--license} {badge-j1--version-latest} {badge-j1-gh--last-commit} {badge-j1--downloads}
endif::[]

// Include sub-documents (if any)
// -----------------------------------------------------------------------------

== Interested in working _with_ or _in_ the Chevrette Lab?

'''

=== Graduate Students

We enthusiastically welcome prospective students to visit and rotate in our lab in order to experience our training philosophy and learn more about current projects. Please contact Marc Chevrette at chevrette (at) wisc (dot) edu about potential rotations, indicating your research interests and why you'd like to work with us. If you have yet to apply to graduate school, https://plantpath.wisc.edu/graduate-study-overview/[click here] to learn more about graduate studies in our home department of Plant Pathology @ UW.

The Chevrette Lab currently accepts graduate students from the following programs:

* https://plantpath.wisc.edu/graduate-study-overview/[Plant Pathology]
* https://genetics.wisc.edu/ph-d-program/[Genetics Training Program]
* https://cmb.wisc.edu/[Cell and Molecular Biology Graduate Program]
* https://biophysics.wisc.edu/[Biophysics (Structural and Computational Biology and Quantitative Biosciences]

'''

=== Postdoctoral applicants

Please send a cover letter indicating your specific motivations for applying to the lab, a CV, and three letters of recommendation to chevrette (at) wisc (dot) edu

'''

=== Collaborations

If you are interested in a collaboration please contact Marc at chevrette (at) wisc (dot) edu for more information.

'''

=== Undergraduates

We occasionally have positions for undergraduate researchers. An excellent work ethic, flexible schedule, and genuine interest in laboratory research are required attributes of all prospective applicants. Undergraduates are required to work for at least one year in our group. Students beginning their sophomore or junior year are preferred. Interested students should email Dr. Chevrette at chevrette (at) wisc (dot) edu. The email should indicate why you would like to join the lab, your expected graduation date, post-graduation plans (if known), and include the contact information for at least one personal reference (ideally a professor or TA). Please indicate whether you are interested in an hourly wage or research credit. Individuals from underrepresented groups in science are especially encouraged to apply.