---
title:                                  Chevrette Lab
tagline:                                Lab Principles
date:                                   2022-06-04 00:00:00
description: >
                                        What we hold important.

tags:                                   [ Overview ]
categories:                             [ Diversity, Inclusion, Principles, Mentorship ]

scrollbar:                              false

permalink:                              /pages/public/lab_principles/site/
regenerate:                             false

resources:                              [ animate, scroller ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/modules/attics/uf_back_blue.jpg
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:badges-enabled:                        false

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ifeval::[{badges-enabled} == true]
{badge-j1--license} {badge-j1--version-latest} {badge-j1-gh--last-commit} {badge-j1--downloads}
endif::[]

// Include sub-documents (if any)
// -----------------------------------------------------------------------------

== Diversity is essential for great science. 

Research and our experience both show that diverse groups generate better ideas and more creative solutions to problems than homogeneous groups. By recruiting diverse people to the Chevrette Lab and empowering every member of our group to contribute to the scientific discourse, we can achieve our scientific potential.

We welcome and value diverse people in our lab and expect each lab member to uphold high standards of integrity and respect. We do not tolerate discrimination based on, but not limited to, ability, age, experience, and identities (e.g. race, ethnicity, gender, sexual orientation, and religion). We believe that each of us has a responsibility to prevent or address unfair behaviors within our lab and scientific environments and to contribute to a welcoming environment.

'''

## We aim to build a safe, welcoming, and supportive lab environment by

- acknowledging each lab member’s needs and unique voice
- trusting one another to hear and be heard
- ensuring that discourse is respectful and supportive
- dynamically assessing the social climate of our lab individually and together to improve the environment for all

'''

== Our lab adheres to the principles of AJEDI

__Antiracism, Justice, Equity, Diversity, & Inclusion__

### Antiracism

Each of us must explicitly and proactively oppose racism in our research, words, and actions.

In our lab::
- we strive to reshape our behavior and biases to actively learn about our scientific history while challenging harmful notions of race and culture
- we speak out against harmful racist language and behavior that is both explicit & implicit

### Justice & Equity

We are all equally deserving of respect and fair treatment. We strive to accept that each of us has unique needs. Intentional action and just behavior prevents and corrects injustice to ensure that all people are treated fairly. 

In our lab::
- we aim to ensure all lab members have equitable access to opportunities and resources for research, science communication, and mentoring
- we each have the responsibility to advocate for ourselves and others and to speak out when opportunity is not offered
- we learn from our mistakes to maintain the safety and respect of each individual

### Diversity 

We are all unique. Our diverse backgrounds and experiences make us better at tackling problems together and are important for our collective success. Diversity is essential to our advancement as a research group and to our growth as human beings. 

In our lab::
- we value the scientific contributions of all lab members and appreciate the inherent dignity and worth of everyone
- we actively seek to engage with distinct individuals, perspectives, and ideas

### Inclusion

We all belong here. 

In our lab::
- we provide mentoring to learn the scientific and cultural aspects of the lab
- we share knowledge for the benefit of all, not the advancement of some
- we promote strong relationships and cultivate a welcoming environment

'''

== The mentor-mentee relationship

My primary teaching goals, both in the lab and in the classroom, are to encourage scientific curiosity and empower problem-solving creativity. Our top priority in higher education should be to instill strong foundations in scientific literacy and critical thinking in our students, independent of their background or ultimate career path. In particular, training in the interpretation of biological data gives students the tools to make sense of the world around them and evaluate new information. From large introductory courses to upper-level undergraduate classrooms, it is necessary to supplement lectures with interactive learning opportunities and exercises to encourage analytical thinking. Graduate-level courses should build towards mastery of relevant literature, reinforce the interdisciplinary nature of science, and advance students’ ability to effectively communicate complex scientific ideas. My goal as a mentor is to help students grow from knowledge consumers into knowledge creators while ensuring trainee metal health and inclusive lab culture. My aim is to provide the foundations and skills for lifelong engagement in STEM. 

Scientific creativity and innovation necessitate diversity. Heterogenous groups foster different approaches and are more creative and thorough than those that lack diversity (Handelsman et al. 2006. Scientific Teaching; McLeod et al. 1996. Small Group Res.). Gender, racial, and ethnic underrepresented groups in STEM make up 68% of undergraduate students, yet their retention in STEM remains a major challenge at every subsequent level (Graham et al. 2013. Science.). While learning experiences are individual, bias can have large impacts on how certain groups experience the scientific environment. Many women and LGBTQ+ students leave science due to alienating and/or hostile environments and black students switch from STEM to non-STEM majors twice as frequently as white students (Handelsman et al. 2006. Scientific Teaching). Minority students at predominantly white institutions experience even greater barriers (Handelsman et al. 2005. Entoring Mentoring.). At some level, these issues stem from (or are exacerbated by) a lack of mentoring. If we are to create an inclusive culture in the classroom and the lab, those in positions of power and privilege must actively and continually assess how the environments they create impact different groups and how to counteract unconscious biases.

Through my experiences, I have learned that a necessary part of being an inclusive mentor is to listen and to seek feedback from peers and trainees that see the world differently or come from different backgrounds. I am committed to using this feedback system to help establish and maintain a culture of acceptance and inclusion in my lab, department, and institution. It is critically important that mentors set standards for maintaining an inclusive, diverse, and anti-racist culture. I will formalize those practices within mentorship contracts that detail the rights and responsibilities of both parties in the mentor-mentee relationship. For those in my lab, I will implement strategies to make myself accessible and to ensure that I monitor my trainees’ mental health and progress in a non-intrusive and careful manner. As individuals, we often do not have the perspective nor the experience to relate to everyone around us. Therefore, we must actively promote inclusive culture for effective trainee mentorship and to connect the diversity of people needed to produce truly innovative thought.

Teaching is not limited to the classroom and mentorship is not limited to one’s own lab. Our lab supports expansive career training, not only to fulfill the university’s research mission, but also to prepare mentees for the many career paths in which their training can make positive impacts on the world.

'''

## My tenets of mentoring

### Growth

Positive scientific, professional, and personal growth is the ideal outcome for menotors and mentees alike. Growth can come in many different and unexpected forms. We will fail, succeed, and grow together. While we strive for positive research outcomes, I will support all mentees' career aspirations and goals, acknowledging that these  will often change over time. Effective mentorship should foster growth in all its forms, above all else.

### Trust

Effective mentorship is built on trust. As a mentor, I will trust that my mentees are being honest with me, discussing the challenges they face both in and (if comfortable) out of the lab. I will trust my mentees are giving their best effort and will engage with me when clarification and/or support are needed. Mentees will have the best experiences if they put their trust in me as a mentor to have their best interests in mind. I acknowledge that this trust is not a given; it must be earned through fostering an environment of authenticity. 

### Authenticity

I firmly believe that one’s best work can only come arise from spaces where one can be their authentic self. Everyone has unique identities and experiences that may or not be shared with me. Thus, it is my responsibility to create a space to allow for mentees to feel comfortable sharing experiences that may be unique to themselves. It’s through sharing these experiences that we can grow. Fostering a welcoming and inclusive environment is vital to successful mentorship and lays the groundwork for open and effective communication.

### Communication

At the core of successful mentorship is communication. I will check in regularly with my mentee to gauge how my mentoring style and the lab's culture is working for them. These conversations will take place privately and will serve as a safe space to discuss any issues that have arisen, either from my perspective or the perspective of my mentee. I will always work to tailor my mentoring style towards the needs of my mentee and provide solutions rooted in experience where appropriate. I acknowledge that there may be instances where I can only offer an ear to listen to my mentee and may not be equipped to offer advice on a particular issue. I aim to be well-versed in resources available for areas outside of my experience and to guide mentees to these resources when appropriate.

'''

_Some sections herein are adapted from the Handelman lab AJEDI statement and Chris Thomas' mentoring philosophy._